/**
 * Message types and type guards for communication between extension and Webview
 */

// ============================================================
// Message Type Constants
// ============================================================

/**
 * Message types sent from extension to Webview
 */
export const ExtensionMessage = {
    NEW_QUESTION: 'newQuestion',
    QUESTION_ANSWERED: 'questionAnswered',
    REMOVE_LAST_QA: 'removeLastQA',
    GENERATING: 'generating',
    SHOW_PLAN: 'showPlan',
    TRANSLATING: 'translating',
    REVISING: 'revising',
} as const;

/**
 * Message types sent from Webview to extension
 */
export const WebviewMessage = {
    ANSWER: 'answer',
    BACK: 'back',
    CANCEL: 'cancel',
    APPROVE_PLAN: 'approvePlan',
    REVISE_PLAN: 'revisePlan',
    TRANSLATE_PLAN: 'translatePlan',
    SHOW_ORIGINAL: 'showOriginal',
} as const;

// ============================================================
// Domain Types
// ============================================================

/**
 * Input schema for the plan tool
 */
export interface PlanToolInput {
    userRequest: string;
    context?: string;
}

/**
 * Question types supported by the UI
 */
export type QuestionType = 'text' | 'select' | 'multiline';

/**
 * Question generated by the subagent
 */
export interface Question {
    text: string;
    type: QuestionType;
    options?: string[];
}

/**
 * Collected answer from user
 */
export interface CollectedAnswer {
    question: string;
    answer: string;
}

/**
 * Response from question generation subagent
 */
export interface QuestionResponse {
    done: boolean;
    question?: Question;
    reason?: string;
}

/**
 * Result type for plan confirmation
 */
export interface ConfirmResult {
    type: 'approve' | 'revise';
    feedback?: string;
}

// ============================================================
// Message Handler Types
// ============================================================

/**
 * Message handler configuration for createPanelPromise
 */
export interface MessageHandler<T> {
    /** The message type to handle */
    type: string;
    /** Handler function that returns the resolved value, or undefined to not resolve */
    handle: (message: Record<string, unknown>) => T | undefined | Promise<T | undefined>;
}

// ============================================================
// Type Guards
// ============================================================

/**
 * Checks if the value is a non-null object
 */
function isObject(value: unknown): value is Record<string, unknown> {
    return typeof value === 'object' && value !== null;
}

/**
 * Validates a Question object
 */
export function isValidQuestion(q: unknown): q is Question {
    if (!isObject(q)) return false;
    if (typeof q.text !== 'string') return false;
    if (!['text', 'select', 'multiline'].includes(q.type as string)) return false;
    if (q.type === 'select' && !Array.isArray(q.options)) return false;
    if (q.options !== undefined && !Array.isArray(q.options)) return false;
    return true;
}

/**
 * Validates a QuestionResponse object
 */
export function isQuestionResponse(obj: unknown): obj is QuestionResponse {
    if (!isObject(obj)) return false;
    if (typeof obj.done !== 'boolean') return false;
    if (obj.question !== undefined && !isValidQuestion(obj.question)) return false;
    if (obj.reason !== undefined && typeof obj.reason !== 'string') return false;
    return true;
}

/**
 * Type guard for answer message
 */
export function isAnswerMessage(msg: Record<string, unknown>): msg is { type: string; answer: string } {
    return typeof msg.answer === 'string';
}

/**
 * Type guard for revise message
 */
export function isReviseMessage(msg: Record<string, unknown>): msg is { type: string; feedback: string } {
    return typeof msg.feedback === 'string';
}

/**
 * Type guard for translate message
 */
export function isTranslateMessage(msg: Record<string, unknown>): msg is { type: string; targetLang: string } {
    return typeof msg.targetLang === 'string';
}
