/**
 * Message types and type guards for communication between extension and Webview.
 * Uses discriminated unions for type-safe message handling.
 */

// ============================================================
// Message Type Constants
// ============================================================

/**
 * Message types sent from extension to Webview
 */
export const ExtensionMessage = {
    NEW_QUESTION: 'newQuestion',
    QUESTION_ANSWERED: 'questionAnswered',
    REMOVE_LAST_QA: 'removeLastQA',
    GENERATING: 'generating',
    SHOW_PLAN: 'showPlan',
    TRANSLATING: 'translating',
    REVISING: 'revising',
} as const;

/**
 * Message types sent from Webview to extension
 */
export const WebviewMessage = {
    ANSWER: 'answer',
    BACK: 'back',
    CANCEL: 'cancel',
    APPROVE_PLAN: 'approvePlan',
    REVISE_PLAN: 'revisePlan',
    TRANSLATE_PLAN: 'translatePlan',
    SHOW_ORIGINAL: 'showOriginal',
} as const;

// ============================================================
// Domain Types
// ============================================================

/**
 * Input schema for the plan tool
 */
export interface PlanToolInput {
    userRequest: string;
    context?: string;
}

/**
 * Question types supported by the UI
 */
export type QuestionType = 'text' | 'select' | 'multiline';

/**
 * Question generated by the subagent
 */
export interface Question {
    text: string;
    type: QuestionType;
    options?: string[];
}

/**
 * Collected answer from user
 */
export interface CollectedAnswer {
    question: string;
    answer: string;
}

/**
 * Response from question generation subagent
 */
export interface QuestionResponse {
    done: boolean;
    question?: Question;
    reason?: string;
}

/**
 * Result type for plan confirmation
 */
export interface ConfirmResult {
    type: 'approve' | 'revise';
    feedback?: string;
}

// ============================================================
// Discriminated Union Message Types
// ============================================================

/**
 * Messages sent from Webview to extension (incoming messages).
 * Using discriminated unions for type-safe handling.
 */
export type WebviewIncomingMessage =
    | { type: typeof WebviewMessage.ANSWER; answer: string }
    | { type: typeof WebviewMessage.BACK }
    | { type: typeof WebviewMessage.CANCEL }
    | { type: typeof WebviewMessage.APPROVE_PLAN }
    | { type: typeof WebviewMessage.REVISE_PLAN; feedback: string }
    | { type: typeof WebviewMessage.TRANSLATE_PLAN; targetLang: string }
    | { type: typeof WebviewMessage.SHOW_ORIGINAL };

/**
 * Messages sent from extension to Webview (outgoing messages).
 */
export type ExtensionOutgoingMessage =
    | { type: typeof ExtensionMessage.NEW_QUESTION; questionNum: number; question: Question; canGoBack: boolean }
    | { type: typeof ExtensionMessage.QUESTION_ANSWERED; questionNum: number; question: string; answer: string }
    | { type: typeof ExtensionMessage.REMOVE_LAST_QA }
    | { type: typeof ExtensionMessage.GENERATING }
    | { type: typeof ExtensionMessage.SHOW_PLAN; plan: string; isTranslated: boolean }
    | { type: typeof ExtensionMessage.TRANSLATING }
    | { type: typeof ExtensionMessage.REVISING };

// ============================================================
// Message Handler Types
// ============================================================

/**
 * Message handler configuration for createPanelPromise
 */
export interface MessageHandler<T> {
    /** The message type to handle */
    type: string;
    /** Handler function that returns the resolved value, or undefined to not resolve */
    handle: (message: WebviewIncomingMessage) => T | undefined | Promise<T | undefined>;
}

// ============================================================
// Type Guards
// ============================================================

/**
 * Checks if the value is a non-null object
 */
function isObject(value: unknown): value is Record<string, unknown> {
    return typeof value === 'object' && value !== null;
}

/**
 * Validates a Question object
 */
export function isValidQuestion(q: unknown): q is Question {
    if (!isObject(q)) return false;
    if (typeof q.text !== 'string') return false;
    if (!['text', 'select', 'multiline'].includes(q.type as string)) return false;
    if (q.type === 'select' && !Array.isArray(q.options)) return false;
    if (q.options !== undefined && !Array.isArray(q.options)) return false;
    return true;
}

/**
 * Validates a QuestionResponse object
 */
export function isQuestionResponse(obj: unknown): obj is QuestionResponse {
    if (!isObject(obj)) return false;
    if (typeof obj.done !== 'boolean') return false;
    if (obj.question !== undefined && !isValidQuestion(obj.question)) return false;
    if (obj.reason !== undefined && typeof obj.reason !== 'string') return false;
    return true;
}

/**
 * Type guard for any webview message (validates basic structure)
 */
export function isWebviewMessage(msg: unknown): msg is WebviewIncomingMessage {
    if (!isObject(msg)) return false;
    if (typeof msg.type !== 'string') return false;
    return Object.values(WebviewMessage).includes(msg.type as typeof WebviewMessage[keyof typeof WebviewMessage]);
}

/**
 * Type guard for answer message
 */
export function isAnswerMessage(msg: WebviewIncomingMessage): msg is { type: typeof WebviewMessage.ANSWER; answer: string } {
    return msg.type === WebviewMessage.ANSWER && 'answer' in msg && typeof msg.answer === 'string';
}

/**
 * Type guard for revise message
 */
export function isReviseMessage(msg: WebviewIncomingMessage): msg is { type: typeof WebviewMessage.REVISE_PLAN; feedback: string } {
    return msg.type === WebviewMessage.REVISE_PLAN && 'feedback' in msg && typeof msg.feedback === 'string';
}

/**
 * Type guard for translate message
 */
export function isTranslateMessage(msg: WebviewIncomingMessage): msg is { type: typeof WebviewMessage.TRANSLATE_PLAN; targetLang: string } {
    return msg.type === WebviewMessage.TRANSLATE_PLAN && 'targetLang' in msg && typeof msg.targetLang === 'string';
}
