/**
 * Message types and type guards for communication between extension and Webview.
 * Uses discriminated unions for type-safe message handling.
 */

// ============================================================
// Message Type Constants
// ============================================================

/**
 * Message types sent from extension to Webview
 */
export const ExtensionMessage = {
    NEW_QUESTION: 'newQuestion',
    QUESTION_ANSWERED: 'questionAnswered',
    REMOVE_LAST_QA: 'removeLastQA',
    GENERATING: 'generating',
    SHOW_PLAN: 'showPlan',
    TRANSLATING: 'translating',
    REVISING: 'revising',
} as const;

/**
 * Message types sent from Webview to extension
 */
export const WebviewMessage = {
    ANSWER: 'answer',
    BACK: 'back',
    CANCEL: 'cancel',
    APPROVE_PLAN: 'approvePlan',
    REVISE_PLAN: 'revisePlan',
    TRANSLATE_PLAN: 'translatePlan',
    SHOW_ORIGINAL: 'showOriginal',
} as const;

// ============================================================
// Domain Types
// ============================================================

/**
 * Input schema for the plan tool
 */
export interface PlanToolInput {
    userRequest: string;
    context?: string;
}

/**
 * Question types supported by the UI
 */
export type QuestionType = 'text' | 'select' | 'multiline';

/**
 * Question generated by the subagent
 */
export interface Question {
    text: string;
    type: QuestionType;
    options?: string[];
}

/**
 * Collected answer from user
 */
export interface CollectedAnswer {
    question: string;
    answer: string;
}

/**
 * Response from question generation subagent
 */
export interface QuestionResponse {
    done: boolean;
    question?: Question;
    reason?: string;
}

/**
 * Result type for plan confirmation
 */
export interface ConfirmResult {
    type: 'approve' | 'revise';
    feedback?: string;
}

// ============================================================
// Discriminated Union Message Types
// ============================================================

/**
 * Messages sent from Webview to extension (incoming messages).
 * Using discriminated unions for type-safe handling.
 */
export type WebviewIncomingMessage =
    | { type: typeof WebviewMessage.ANSWER; answer: string }
    | { type: typeof WebviewMessage.BACK }
    | { type: typeof WebviewMessage.CANCEL }
    | { type: typeof WebviewMessage.APPROVE_PLAN }
    | { type: typeof WebviewMessage.REVISE_PLAN; feedback: string }
    | { type: typeof WebviewMessage.TRANSLATE_PLAN; targetLang: string }
    | { type: typeof WebviewMessage.SHOW_ORIGINAL };

/**
 * Messages sent from extension to Webview (outgoing messages).
 */
export type ExtensionOutgoingMessage =
    | { type: typeof ExtensionMessage.NEW_QUESTION; questionNum: number; question: Question; canGoBack: boolean }
    | { type: typeof ExtensionMessage.QUESTION_ANSWERED; questionNum: number; question: string; answer: string }
    | { type: typeof ExtensionMessage.REMOVE_LAST_QA }
    | { type: typeof ExtensionMessage.GENERATING }
    | { type: typeof ExtensionMessage.SHOW_PLAN; plan: string; isTranslated: boolean }
    | { type: typeof ExtensionMessage.TRANSLATING }
    | { type: typeof ExtensionMessage.REVISING };

// ============================================================
// Message Handler Types
// ============================================================

/**
 * Message handler configuration for createPanelPromise
 */
export interface MessageHandler<T> {
    /** The message type to handle */
    type: string;
    /** Handler function that returns the resolved value, or undefined to not resolve */
    handle: (message: WebviewIncomingMessage) => T | undefined | Promise<T | undefined>;
}

// ============================================================
// Type Guards (re-exported from guards module)
// ============================================================

export {
    isValidQuestion,
    isQuestionResponse,
    isWebviewMessage,
    isAnswerMessage,
    isReviseMessage,
    isTranslateMessage,
} from './guards';
